{
    "name": "Refuge des Aventuriers — Core",
    "summary": "Configuration Odoo du bar Le Refuge des Aventuriers "
               "(catalogue, clients, fournisseurs, BoM cocktails, fidélité, POS, employés).",
    "version": "17.0.1.0.0",
    "author": "Équipe SAÉ 6.Integ.01",
    "license": "AGPL-3",
    "category": "Point of Sale",
    "depends": [
        "base",
        "contacts",
        "product",
        "stock",
        "mrp",
        "purchase",
        "purchase_stock",
        "point_of_sale",
        "pos_loyalty",
        "loyalty",
        "hr",
        "hr_contract",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/refuge_staff_groups.xml",
        "data/product_category.xml",
        "data/res_partner.xml",
        "data/product_template.xml",
        "data/product_supplierinfo.xml",
        "data/mrp_bom.xml",
        "data/loyalty_program.xml",
        "data/hr_employee.xml",
        "data/refuge_staff_contracts.xml",
        "data/refuge_staff_users.xml",
        "data/pos_config.xml",
        "data/refuge_demo_setup.xml",
        "views/res_partner_views.xml",
        "views/product_template_views.xml",
        "views/hr_employee_views.xml",
        "views/stock_alert_views.xml",
        "views/menu_views.xml",
    ],
    "post_init_hook": "post_init_refuge_staff",
    "application": True,
    "installable": True,
}
